dist: xenial
language: node_js
node_js: lts/*
os: linux
jobs:
  include:
    - stage: direflow
      before_install:
        - "cd direflow"
      install:
        - "npm ci"
      script: "npm run test:ci"
      deploy:
        provider: script
        script: "npm publish"
        on:
          branch: main
          skip_cleanup: true
