dist: xenial
language: node_js
node_js: lts/*
os: linux
jobs:
  include:
    - stage: direflow
      before_install:
        - "cd ${TRAVIS_BUILD_DIR}/direflow"
      install:
        - "npm ci"
      script: "npm run test:ci"
    - stage: lit-element
      before_install:
        - "cd ${TRAVIS_BUILD_DIR}/lit-element"
      install:
        - "npm ci"
      script: "npm run test"
    - stage: stencil
      before_install:
        - "cd ${TRAVIS_BUILD_DIR}/stencil"
      install:
        - "npm ci"
      script: "npm run test:ci"
